ApplyInfo 페이지
mju-likelion/x-rated pull request #1
Opened 2023-01-23 10:59 UTC by ChoiWonYu

2023-01-23 14:34 UTC, Bhanjo commented on src/pages/ApplyInfo/ButtonBox.js
> +import React from 'react';
import문에서 react는 굳이 없어도 됩니다! 만약 lint 때문이라면 이 규칙은 없애는게 좋겠네요

2023-01-23 14:34 UTC, Bhanjo commented on src/pages/ApplyInfo/ButtonBox.js
> +  const isSelected = value => (value === selectedValue ? 'selected' : '');
이름이 is~인데 반환값은 string이네요 이거는 특별한 이유가 아니라면 bool 값을 받는게 추후 유지보수에 편해보입니다!

2023-01-23 14:34 UTC, Bhanjo commented on src/pages/ApplyInfo/index.js
> +          <ButtonBox name="campus" buttonData={CAMPUS} />
ButtonBox라는게 정확히 어떤의미인가요?? figma를 봤을 땐 radio 버튼으로 판단되는데, radio button이 맞다면 이름을 수정하는게 좋아보이는데 어떤가요?

2023-01-23 14:35 UTC, Bhanjo approved these changes

2023-01-23 14:55 UTC, ChoiWonYu commented on src/pages/ApplyInfo/index.js
> +          <ButtonBox name="campus" buttonData={CAMPUS} />
Radiobutton은 CheckBox이고,
ButtonBox는 버튼이 선택값인 질문입니다!
피그마에서는 캠퍼스, 학적, 지원파트입니당

2023-01-23 15:38 UTC, Bhanjo commented on src/pages/ApplyInfo/index.js
> +          <ButtonBox name="campus" buttonData={CAMPUS} />
아 이미 네이밍이 그렇게 된건가요? 그럼 괜찮아보입니다 bb

2023-01-23 18:05 UTC, harksu requested changes
굳이... 싶긴하지만, 그래두 커밋 컨벤션을 사전에 정의했으니 커밋 메시지를 두 줄로 변경하면 어떨까요 ~?
git commit -amend라는 좋은 친구가 있습니다 :)

2023-01-23 18:06 UTC, harksu approved these changes

2023-01-23 20:57 UTC, harksu commented on src/pages/ApplyInfo/data/ButtonData.js
> +export const Academic = ['재학', '휴학'];
데이터에 관련된 파일을 별도로 분리한다는것에 대해선 아주 찬성이지만 👍 , 이걸 페이지 폴더 밑에 Data라는 폴더로 또 나눠야할지가 의문입니다.
나누지않아도 이 데이터들은 해당 페이지에서만 사용하는 값들이라, 오히려 구조가 복잡해지는 느낌입니다.

2023-01-23 21:16 UTC, ChoiWonYu commented on src/pages/ApplyInfo/data/ButtonData.js
> +export const Academic = ['재학', '휴학'];
좋은 의견 감사합니다! 저는 컴포넌트 파일 확장자가 jsx가 아니라서 일반 데이터 파일과의 구분을 위해서 data 폴더를 따로 만든건데 그래도 역시 폴더가 없는 게 나을까요??

2023-01-23 21:57 UTC, harksu commented on src/pages/ApplyInfo/data/ButtonData.js
> +export const Academic = ['재학', '휴학'];
개인적으로 저는 없는게 더 보기 좋은 것 같다고 생각합니다 :) page 폴더 하위에서 page에 대한 폴더 이름이 다시 명시가 되어있으니까요..!
다른분들도 이 부분에 대해서 함께 생각해보고, 통일된 방향으로 진행하는게 더 좋을 것 같다는 생각입니다 👍

2023-01-24 10:37 UTC, yhyem approved these changes

2023-01-24 10:37 UTC, yhyem commented on src/pages/ApplyInfo/data/ButtonData.js
> +export const Academic = ['재학', '휴학'];
음 저도 다른 곳에도 필요한 Data 가 아니라 해당 페이지에서만 사용하는 거라 페이지 폴더 안에 있는 편이 조금 더 관리하기 편하지 않을까라는 생각이 있습니다!

2023-01-24 11:29 UTC, ChoiWonYu commented on src/pages/ApplyInfo/data/ButtonData.js
> +export const Academic = ['재학', '휴학'];
아하 그렇네요 그럼 그렇게 수정하겠습니다!

2023-01-26 10:42 UTC, Bhanjo commented on src/pages/ApplyInfo/ButtonBox.js
> +          }}
jsx 안에 함수 로직은 지양해주세요!

2023-01-26 10:42 UTC, Bhanjo commented on src/pages/ApplyInfo/SelectBox.js
> +      </select>
이거랑 input 처럼 html에 props 넣은것들은 아직 미완성인거죠??

2023-01-26 10:42 UTC, Bhanjo commented on src/pages/ApplyInfo/ButtonBox.js
> +export default ButtonBox;
저번에도 말했던 것 같은데 잊어버려서..
이거의 경우 n개의 선택지 중 반드시 하나만 선택하는 ui인데, ux적으로도 그렇고 radio로 구현하는게 훨씬 더 로직상 편해보이는데 button으로 구현한 이유가 있을까요?
radio로 하면 change 로직 같은거 훨씬 더 간단해질 것 같다고 생각했어요

2023-01-26 12:48 UTC, harksu reviewed
👍

2023-01-26 12:48 UTC, harksu commented on src/pages/ApplyInfo/SelectBox.js
> +      </select>
key값으로 data보다는 다른 unique value가 더 좋을 것 같다는 생각이 스쳐지나갑니다..! 
아니면 data.property 같은 조금 더 구체화 된 unique value 가 좋을 것 같아요 👍

2023-01-26 13:00 UTC, ndaemy commented on src/pages/ApplyInfo/ButtonBox.js
> +export default ButtonBox;
[HTML Semantic tag](https://www.w3schools.com/html/html5_semantic_elements.asp)에도 반대되는 코드입니다. 수정하는걸 추천드려요

2023-01-26 13:00 UTC, ndaemy commented on src/pages/ApplyInfo/ButtonData.js
> +export const ENROLLMENTSTATUS = ['enrolled', 'tookOff'];
서버는 이거 짜증나서 한글로 바꿨습니다. 그냥 ENROLLMENTSTATUS 로 통일해도 될 것 같아요.

2023-01-26 13:00 UTC, ndaemy commented on src/pages/ApplyInfo/FormikConfig.js
> +    cautionConfirm: Yup.boolean().required().oneOf([true]),
하여간 validation logic 이 제일 귀찮죠

2023-01-26 13:02 UTC, ndaemy commented on src/pages/ApplyInfo/index.js
> +      <Formik
formik 을 hook 을 통해 쓸건지 component 형으로 쓸건지 통일되면 다른 작업자들도 적은 공수로 코드를 이해할 수 있을 것 같아요

2023-01-26 17:11 UTC, ChoiWonYu commented on src/pages/ApplyInfo/ButtonBox.js
> +export default ButtonBox;
피그마에 캠퍼스, 학적, 지원파트처럼 버튼을 선택하는 걸 radio로 구현할 수 있나요..???

2023-01-27 15:52 UTC, ndaemy requested changes

2023-01-27 15:52 UTC, ndaemy commented on src/pages/ApplyInfo/ButtonBox.js
> +      {field.value && meta.touched && meta.error ? <div>{meta.error}</div> : null}
조건부 렌더링일때는 굳이 삼항연산자일 필요 없습니다. 아래 suggestion 으로도 충분해요

```suggestion
      {field.value && meta.touched && meta.error && <div>{meta.error}</div>}
```

2023-01-27 15:52 UTC, ndaemy commented on src/pages/ApplyInfo/FormikConfig.js
> +  }),
validationSchema 를 통째로 객체로 분리시켜보는건 어떨까요?

2023-01-27 15:52 UTC, ndaemy commented on src/pages/ApplyInfo/index.js
> +            <ProgressButton type="submit" disabled={Object.keys(errors).length > 0}>
lodash의 _.isEmpty 같은걸 써보는것도 방법일듯 합니당 (조금 더 명확한 이름이니까요)

2023-01-27 16:02 UTC, ndaemy commented
그리고 PR 이름이 한글인게 더 잘 이해될 것 같아요

2023-01-27 16:50 UTC, harksu reviewed
고생이 많습니다

2023-01-27 16:50 UTC, harksu commented on src/pages/ApplyInfo/FormikConfig.js
>      campus: Yup.string().required().oneOf(['자연'], '멋쟁이사자처럼 명지대 인문캠퍼스에 지원해 주세요.'),
👍

2023-01-28 08:38 UTC, ChoiWonYu commented on src/pages/ApplyInfo/index.js
> +            <ProgressButton type="submit" disabled={Object.keys(errors).length > 0}>
lodash를 설치하라는 lint 에러가 뜨네요...

2023-01-28 08:40 UTC, ChoiWonYu commented on src/pages/ApplyInfo/SelectBox.js
> +      </select>
data에 prop이 없어서요...

2023-01-28 08:42 UTC, ChoiWonYu commented on src/pages/ApplyInfo/SelectBox.js
> +      </select>
data가 문자열 형태의 숫자라 다른 unique한 value가 있는지 더 생각해보겠습니당

2023-01-29 13:40 UTC, Bhanjo commented on src/pages/ApplyInfo/index.js
> +              }
삼항연산자에서 분기가 또 나오는 것은 매우 좋지 않은 코드입니다! 삼항연산자는 이분적으로 나눌 수 있는 상황에서만 써주세요! 이경우 차라리 에러 컨트롤 함수와 에러 메시지 상태를 만들어 메시지 state를 전달하는 게 좋아보여요

2023-01-29 14:34 UTC, ChoiWonYu commented on src/pages/ApplyInfo/index.js
> +              }
useFormik과 Field를 같이 쓸 수 없어서 Formik을 컴포넌트로 이용해야 하는데
그렇게 되면 errors 객체에 접근할 수 있는 게 JSX 내부밖에 없어서 ErrorFinder 컴포넌트를 따로 만들어야 할 것 같은데
삼항연산자를 여러 번 사용하는 것보다는 이게 나을까요??

2023-01-30 00:10 UTC, Bhanjo commented on src/pages/ApplyInfo/index.js
> +              }
구조가 너무 복잡한데요..? 리팩터링 할 시간 없으면 우선 이거는 추후 수정하는거로 해요!

2023-02-01 04:44 UTC, harksu reviewed
커스텀이 많다보니 컴포넌트 또한 많네요... 고생이 많으셨습니다 👍

2023-02-01 04:44 UTC, harksu commented on src/pages/ApplyInfo/index.js
> +                      !values.name
해당 부분에 대해서 함수 호출로.. 바꾸면 어떨까 하는 생각이 조심스럽게 듭니다
에러 조건부가 복잡한건 이해하지만서도 jsx 내부에서 조건문이 너무 복잡해서 가독성이 좋지 않은 것 같아요!

2023-02-01 04:44 UTC, harksu commented on src/pages/ApplyInfo/index.js
> +    width: 1200px;
width를 1200px을 준상태에서 max-width는 의미가 없지않나요 ?

2023-02-01 14:47 UTC, ndaemy requested changes

2023-02-01 14:47 UTC, ndaemy commented on src/pages/ApplyInfo/ButtonBox.js
> +const ButtonBox = ({ buttonData, name, text }) => {
buttonData 가 만약 배열이라면 복수형을 쓰는게 더 알아보기 쉬울 것 같아요
buttonsData 라던가?

2023-02-01 14:47 UTC, ndaemy commented on src/pages/ApplyInfo/ButtonBox.js
> +  }
기본 값은 미디어쿼리로 감싸지 말아주세요! 이러면 350px 미만에 대해서는 아무 값이 들어가지 않기 때문에 심각하게 깨집니다!

2023-02-01 14:47 UTC, ndaemy commented on src/pages/ApplyInfo/CheckBox.js
> +  appearance: none;
어차피 다 커스텀하는데 이게 들어가야 하는 이유가 따로 있어서 넣은건가요..?

2023-02-01 14:47 UTC, ndaemy commented on src/pages/ApplyInfo/Validation.js
> +    .matches(/^01([0|1|6|7|8|9])-([0-9]{3,4})-([0-9]{4})$/, 'form'),
요거 서버랑 맞춰주세요..! 안그러면 웹 validation 은 통과해놓고 서버는 통과 못하는 일이 생길수도 있어서요..!

2023-02-01 14:47 UTC, ndaemy commented on src/pages/ApplyInfo/index.js
> +                  <TextInput name="phone" type="text" placeholder="000-0000-0000" text="전화번호" maxLength={13} />
이거 숫자가 아닌건 입력 못 받게 처리해주셔야 하고, `-`는 자동으로 입력되게 처리해주셔야 합니다..!

2023-02-01 15:02 UTC, harksu commented on src/pages/ApplyInfo/ButtonBox.js
> +  }
이 부분에 대해서는 제가 슬랙에 언급하겠습니다

2023-02-01 15:03 UTC, harksu commented on src/pages/ApplyInfo/index.js
> +                  <TextInput name="phone" type="text" placeholder="000-0000-0000" text="전화번호" maxLength={13} />
이런 기능적인 부분은 사실, 추후에 브랜치 분기해서 추가 작업하셔도 될 것 같아요..! 디자인 취합이 조금 더 급한 부분이라서

2023-02-01 15:18 UTC, Bhanjo approved these changes
언급 된 것들 수정되면 merge 하셔도 됩니다~ 고생하셨어요 bbb

2023-02-01 15:18 UTC, Bhanjo commented on src/pages/ApplyInfo/CheckBox.js
> +  border: 1px solid gainsboro;
`gainsboro` 라는 색이 figma에서 명시된 색인가요..? 처음 들어보는 색이라ㄷㄷ

2023-02-01 15:18 UTC, Bhanjo commented on src/pages/ApplyInfo/DropDown.js
> +  }, [outsideRef]);
리액트에서 dom을 직접 건드리는건 안 좋은 방법인데 이 방법 말곤 없었나요??

2023-02-01 15:18 UTC, Bhanjo commented on src/pages/ApplyInfo/DropDown.js
> +  }
의도가 마지막 자식 요소의 마진을 0으로 하고 싶은 것 같은데, `nth-child`로 하드하게 지정하는 것보다 `last-child` 속성을 이용하는게 의도에 맞는 표현인 것 같아요!

2023-02-01 15:28 UTC, mywhzy approved these changes
세상에 이게 다 몇 줄이야... 넘나리 고생하셨습니다아 🙌🏻

2023-02-01 15:48 UTC, ChoiWonYu commented on src/pages/ApplyInfo/CheckBox.js
> +  border: 1px solid gainsboro;
제 실수였네요..ㅎ 찾아주셔서 감사합니다

2023-02-01 15:48 UTC, ChoiWonYu commented on src/pages/ApplyInfo/CheckBox.js
> +  appearance: none;
(https://dev.to/tomdohnal/custom-checkbox-in-react-animated-and-accessible-3jk9)
이런 이유로 input label로 묶어서 구현하라고 하더라구요...

2023-02-01 15:51 UTC, ChoiWonYu commented on src/pages/ApplyInfo/DropDown.js
> +  }, [outsideRef]);
버튼 에러 메세지 전달이랑 이 문제 같은 기능적인 부분은 추후에 브랜치 파서 수정해보겠습니다 감사합니다!

2023-02-01 16:17 UTC, ndaemy requested changes

2023-02-01 16:17 UTC, ndaemy commented on src/pages/ApplyInfo/index.js
> +    margin-bottom: 50px 0;
margin-bottom 인데 어떻게 두 인자를 받을 수 있죠..?

2023-02-01 16:17 UTC, ndaemy commented on src/pages/ApplyInfo/index.js
> +    margin-bottom: 4px 0 40px 0;
여기도..

2023-02-01 16:20 UTC, ndaemy commented on src/pages/ApplyInfo/index.js
> +  const FORMERROR = '형식에 맞지 않는 값이 존재합니다.';
1. 상수는 컴퍼넌트 밖으로 빼주세요!
2. 상수 네이밍은 UPPER_CASE 입니다! UPPERCASE가 아니구요!

2023-02-01 16:20 UTC, ndaemy commented on src/pages/ApplyInfo/index.js
> +  const FORMERROR = '형식에 맞지 않는 값이 존재합니다.';
아 그리고 이거 객체로 감싸도 괜찮을 것 같아요. 아니면 모든 에러 메세지들을 하나의 파일에서 관리해도 좋을 것 같구요.

2023-02-01 16:21 UTC, ndaemy commented on src/pages/ApplyInfo/index.js
> +  const FORMERROR = '형식에 맞지 않는 값이 존재합니다.';
비슷하게 에러 상수가 많을 것 같은 @harksu 도 참고우

2023-02-01 16:22 UTC, ChoiWonYu commented on src/pages/ApplyInfo/Validation.js
> +    .matches(/^01([0|1|6|7|8|9])-([0-9]{3,4})-([0-9]{4})$/, 'form'),
이거 변경된 유효성 검사 커밋 봐주실 수 있나요??
띄워주는 값이 '-'가 붙는 값이라 유효성 검사는 변경 사항과 같이 하고,
서버에 보낼 때 '-'를 제거하고 보내려고 하는데 괜찮을까요??

2023-02-01 16:23 UTC, ChoiWonYu commented on src/pages/ApplyInfo/index.js
> +                  <TextInput name="phone" type="text" placeholder="000-0000-0000" text="전화번호" maxLength={13} />
넵 이건 머지된 이후에 브랜치 따로 파서 수정하겠습니다!

2023-02-01 17:35 UTC, ndaemy approved these changes
크리티컬한 이슈는 안보입니다! 수고하셨습니다 👏

2023-02-01 17:35 UTC, ndaemy commented on src/pages/ApplyInfo/ButtonBox.js
> +import { StyledText } from './TextInput';
이렇게 자주 쓰이는 녀석이면 아예 별도의 파일로 빼보는건 어떨까요?

2023-02-01 17:35 UTC, ndaemy commented on src/pages/ApplyInfo/TextInput.js
> +  font-family: 'Spoqa Han Sans Neo', 'Spoqa Han Sans JP', sans-serif;
이거 여기서 별도로 선언해야만 하나요?

2023-02-01 17:40 UTC, ChoiWonYu commented on src/pages/ApplyInfo/ButtonBox.js
> +import { StyledText } from './TextInput';
이건 리팩터링 할 때 공통으로 쓰이는 것들이 또 있다면 합쳐서 만들어보겠습니다!

2023-02-01 17:41 UTC, merged