토스트 메시지 컴포넌트 구현
mju-likelion/x-rated pull request #11
Opened 2023-01-31 05:35 UTC by mywhzy

2023-01-31 07:18 UTC, harksu requested changes
공통 컴포넌트를 구현할 땐, 교육팀장님이 저번에 올렸던 풀리퀘스트처럼 짧은 데모 영상을 첨부주시면 더 좋을 것 같아요👍
어떤식으로 작동이 되는지에 대해서 코드만으로 유추하는 것은 힘드니까요!

2023-01-31 07:18 UTC, harksu commented on src/components/Toast.js
> +import toastErrorIcon from '../assets/images/icon_type_error.svg';
지난 리뷰에서 svgr로 사용하는 것에 대한 문의가 들어왔던 것 같은데, 이 부분은 패스하기로 결정이 난건가요?
만약 svgr이라면 통일하는게 더 좋을 것 같습니다 👍

2023-01-31 07:18 UTC, harksu commented on src/components/Toast.js
> +    }, 1500);
1.5초로 PM님과 결정이 된건지 궁금합니다  (정말 몰라서 질문드리는거에요!!!)

2023-01-31 07:18 UTC, harksu commented on src/components/Toast.js
> +      <ToastTypeIcon src={type === 'success' ? toastSuccessIcon : toastErrorIcon} />
type보다는 messageType, toastType과 같은 네이밍이 다소 길더라도 가독성이나 추후 확장성 측면에서 좋지 않을까.. 라는 생각입니다.
저희 프로젝트에선 TS를 사용하진 않지만 개인적으로는 보자마자 조금 헷갈렸어요!

2023-01-31 07:43 UTC, harksu commented on src/components/Toast.js
> +      <ToastTypeIcon src={type === 'success' ? toastSuccessIcon : toastErrorIcon} />
이건 다른 분들 의견도 여쭤보고 편하신대로 하시면 될 것 같아요!
(이제 보니 공통 버튼에도 type으로 지어져있어서 컴포넌트명으로 구분을 해도 괜찮겠다는 생각이 듭니다)

2023-01-31 15:06 UTC, mywhzy commented on src/components/Toast.js
> +import toastErrorIcon from '../assets/images/icon_type_error.svg';
요거 아직 웹짱님과 논의를 안 해봐서!.. 논의 후에 말씀드리겠습니다

2023-01-31 15:08 UTC, mywhzy commented on src/components/Toast.js
> +    }, 1500);
이 부분 제가 작업할 때는 결정사항이 아니었습니다ㅜㅜ PM님과 논의했더니 디자이너님께 컨펌 받아달라고 하셔서 디자이너님과 2초로 결정했습니다!

2023-01-31 15:09 UTC, mywhzy commented on src/components/Toast.js
> +      <ToastTypeIcon src={type === 'success' ? toastSuccessIcon : toastErrorIcon} />
움 둘 중에 고민하다가 toastType으로 일단 props명 변경했습니다! 다른 분들도 의견 주시면 반영하겠습니당

2023-01-31 15:41 UTC, harksu commented
z-index 속성으로 표면적으로 가장 위에서 렌더링 되는건 정말 좋습니다 👍 
토스트 메시지가 렌더링 되는 위치가 조금 애매한 것 같은데, 혹시 해당 사항도 논의가 된 사항일까요?

2023-02-01 05:14 UTC, harksu approved these changes
나중에 헤더랑 푸터 합쳤을 때, 위치 디테일 수정 잡으면 될 것 같습니다 :)

2023-02-01 05:22 UTC, Bhanjo approved these changes
포지션에 관해서 좀 따져야 될 게 많은데.. 우선 시간이 없으니 차차 개선하면 될 것 같습니다~

2023-02-01 05:22 UTC, Bhanjo commented on src/components/Toast.js
> +    };
오 뒷정리함수 굳

2023-02-01 05:22 UTC, Bhanjo commented on src/components/Toast.js
> +      <ToastTypeIcon src={toastType === 'success' ? toastSuccessIcon : toastErrorIcon} />
삼항 연산 같은 경우 boolean 값으로 판단하는데 만약 `success`를 휴먼미스테이크로 `succe` 하게 된다면 성공인데 실패 아이콘이 뜰 수 있어요!

결론은 삼항연산자로 구분하려면 toastType를 string이 아닌 boolean으로 가는 것이 좀 더 올바른 방법입니다

이건 당장 수정 가능하면 바꾸는 게 좋고 아니라면 추후 수정하는 걸로 해요~

2023-02-01 06:22 UTC, harksu commented on src/components/Toast.js
> +    };
ㅇㅈ

2023-02-01 06:32 UTC, mywhzy commented on src/components/Toast.js
> +      <ToastTypeIcon src={toastType === 'success' ? toastSuccessIcon : toastErrorIcon} />
아하.. 불리안이 휴먼 에러를 생각하면 훨씬 좋은거군여 사용의 이유를 다시 깨달았습니다 요거 피드백 반영해서
우선 변수명 `isSuccess`로 변경했습니다! 추후에 의견 들어오면 또 반영해보겠습니당

2023-02-01 06:33 UTC, mywhzy commented on src/components/Toast.js
> +    };
구글이..도와준거지만 일단 감사합니다^^ 이해하면서 사용한거니까..?ㅎ

2023-02-01 06:48 UTC, mywhzy commented
> 포지션에 관해서 좀 따져야 될 게 많은데.. 우선 시간이 없으니 차차 개선하면 될 것 같습니다~

 요거 일단은 저두 피드백 받구 수정해야될 거 같애서.. `translate:transform(-50%,-50%)`
이거 일단 추가해서 중앙정렬 되게끔만 시도해봤습니다아...

2023-02-01 07:29 UTC, merged