Feature/apply write page
mju-likelion/x-rated pull request #2
Opened 2023-01-23 22:08 UTC by harksu

2023-01-23 22:12 UTC, harksu commented
김밥을 좀 크게 썰었습니다 죄송합니다

2023-01-24 02:28 UTC, Bhanjo commented on src/pages/ApplyWrite/index.js
> +          );
나중에 기회 된다면 이부분을 컴포넌트로 빼는 것도 좋을 것 같아요!

2023-01-24 02:28 UTC, Bhanjo commented on src/pages/ApplyWrite/index.js
> +
상속 받은 것은 좋은데 `WriteTitle`과 `WriteLength`와의 연관 관계가 맞지 않아보여요
title은 제목의 스타일링인데, length는 글자 카운트를 위한 것이라 나중에 페이지가 복잡해지면 이 둘이 서로 관계가 있는걸 놓치기 쉬워질 것 같습니다!

2023-01-24 12:16 UTC, ChoiWonYu reviewed
고생하셨습니다!

2023-01-24 12:16 UTC, ChoiWonYu commented on src/pages/ApplyWrite/index.js
> +  background-color: white;
이 코드는 테스트용이었던 코드인가요?

2023-01-24 12:34 UTC, ndaemy commented on src/pages/ApplyWrite/index.js
> +  background-color: ${props => props.theme.Colors.GRAY1};
desctructuring 하는 것도 좋아보여요
하든 안하든은 선택이지만 프로젝트 내부적으로는 통일해서 가시져 (지난번에 @ChoiWonYu 가 destructuring 했던 것으로 기억해서!)

2023-01-24 16:02 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +          );
안그래도 추후에 리팩터링 작업을 거쳐서 컴포넌트로 분리할 계획에 있습니다 :) 👍

2023-01-24 16:03 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +
오옹... 단순히 같은 속성을 공유한다는 생각으로 상속을 사용한건데, 연관 관계를 고려하는 것이 더 좋은 코드가 될 수 있겠군요 :) 수정하도록 하겠습니다!

2023-01-24 16:03 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +  background-color: white;
아,, 넵 영역 확인을 위해서 테스트용 코드였는데, 삭제를 누락했네요..! 제거하도록 하겠습니다 👍

2023-01-24 16:04 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +  background-color: ${props => props.theme.Colors.GRAY1};
좋습니다 👍

2023-01-24 16:10 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +
이미 해놨었네요 핳

2023-01-24 16:14 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +          );
해당 기능을 사용하는 부분은 자기소개서 항목을 작성하는 해당 페이지 내에서가 유일한데, 그래도 컴포넌트로 분리하는 것이 더 좋을까요?

2023-01-25 03:31 UTC, Bhanjo commented on src/pages/ApplyWrite/index.js
> +          );
지금 사이즈에서는 분리 안해도 되지만 추후 규모가 커지면 그때 고민하면 될 것 같아요!

2023-01-25 03:32 UTC, Bhanjo approved these changes

2023-01-26 10:59 UTC, Bhanjo reviewed
textarea에 포커스있을 때 하얀색 테두리 생기는건 의도한 디자인인가요??

2023-01-26 11:36 UTC, Bhanjo commented on src/pages/ApplyWrite/index.js
> +
입력값이 최대 길이를 초과하면 반영이 안되도록 수정했습니다 `42번째 줄`의 경우 조금 더 엄격한 검사를 위해 글자 초과시 return하여 값 반영을 하지 못하도록 변경했습니다.

2023-01-26 12:56 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +
return이 훨씬 명쾌한 것 같네요 👍  나름 테스트 돌린다고 돌린건데, 예외 잡아주신거 아주 감사합니당

2023-01-26 13:33 UTC, ndaemy commented on src/pages/ApplyWrite/index.js
> +                onChange={e => onChange(e, order[index], item.maxLength)}
이거 이렇게.. 밖에 안되나요..? id 랑 name 으로 이케 저케 안되나 싶어서..

2023-01-26 13:33 UTC, ndaemy commented on src/pages/ApplyWrite/index.js
> +                  onChange={e => onChange(e, order[index], item.maxLength)}
이거 이렇게밖에 안되나요..? id 랑 name 으로 이케 저케 안되나 싶어서요..!

2023-01-26 16:53 UTC, ndaemy commented
PR 이름 바꿔주세요~

2023-01-27 06:20 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +                onChange={e => onChange(e, order[index], item.maxLength)}
추후에 확인해보겠습니다 👍

2023-01-27 16:07 UTC, ndaemy requested changes

2023-01-27 16:07 UTC, ndaemy commented on src/pages/ApplyWrite/index.js
> +        }}
가능하다면 함수 선언으로 빼주세요!

2023-01-27 16:07 UTC, ndaemy commented on src/pages/ApplyWrite/index.js
> +                  {formik.values[order[index]].length}/{item.maxLength}
요걸 함수 호출로 바꿔보면 어떨까요?
```suggestion
                  {getCharacterCount(item, index)}
```
이런 식으로요!

2023-01-27 16:07 UTC, ndaemy commented on src/pages/ApplyWrite/index.js
> +  }
요거 저는 디자이너분 의도가 custom scrollbar 는 아니었던거로 알고 있어서 디자이너분하고 컴케 해보셔야 할듯 합니다

2023-01-27 16:52 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +  }
피그마에 명시적으로 스크롤이 나와있던데, 추후에 결재 받아보도록 하겠습니다 👍

2023-01-28 16:20 UTC, harksu commented
커밋 내용 카테고리도 비슷하고 명칭도 똑같아서 커밋을 아예 돌려버릴까 하다가 편의를 위해 별도로 2개의 커밋으로 작성하였습니다.

2023-01-29 13:48 UTC, Bhanjo commented
굳이? 이긴 싶지만.. 커밋 메시지에 `refactor`는 원래 기능을 유지하고 코드 내부 로직을 개선할 때 쓰입니다!

예를들어 [refactor: font left align](https://github.com/mju-likelion/x-rated/pull/2/commits/63346323ae4787482c23a78c0eed89f383186401) 커밋의 경우 chore가 더 맞을 것 같아요

2023-01-31 10:44 UTC, ndaemy commented on src/pages/ApplyWrite/index.js
> +import Button from './../../components/Button';
나아중에 시간 되면.. 이거 relative path import 로 바꾸면 이쁠 것 같아여

2023-01-31 10:44 UTC, ndaemy commented on src/pages/ApplyWrite/index.js
> +                {` ${index + 1}. ${item.question}`}
스페이스보다는 padding을 주는 것도 좋을 것 같아요. SEO 같은거 돌면 스페이스도 파싱해버리니까! (단순 복붙 할때도 그렇구요)

2023-01-31 10:44 UTC, ndaemy commented on src/pages/ApplyWrite/index.js
> +  }
이거 custom scrollbar 아닐 거 같은데.. 디자이너님이랑 얘기 된 부분인가요?

2023-01-31 11:25 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +  }
이거 커스텀 맞습니다!

2023-01-31 11:25 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +                {` ${index + 1}. ${item.question}`}
그러면 이걸 스타일 컴포넌트로 다시 빼는건가요 ? @ndaemy

2023-01-31 11:25 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +import Button from './../../components/Button';
해당 부분에 대해서 현재 브랜치에서 작업하는건 기능적으로 브랜치를 나눈 의미가 없다고 생각해서, 추후에 브랜치 분기후에 작업하겠습니다.
(+++ src를 root로 절대 경로를 설정해버리는 방법도 있긴 하다만, 이건 eslint rule이랑 충돌이 생기고 임의로 결정할 문제는 아니라서 추후에 교육팀장님과 논의해보겠습니다)

2023-01-31 16:01 UTC, ndaemy commented on src/pages/ApplyWrite/index.js
> +                {` ${index + 1}. ${item.question}`}
BaseTitle에 padding-left 를 줘도 되죠?

2023-01-31 16:01 UTC, ndaemy approved these changes

2023-01-31 16:02 UTC, harksu commented on src/pages/ApplyWrite/index.js
> +                {` ${index + 1}. ${item.question}`}
혹시.. 천재?

2023-01-31 16:30 UTC, merged