지원 완료 페이지 구현
mju-likelion/x-rated pull request #22
Opened 2023-02-03 14:42 UTC by mywhzy

2023-02-03 16:19 UTC, harksu requested changes
컴포넌트 반복만 줄이면 괜찮을 것 같습니다!

2023-02-03 16:19 UTC, harksu commented on src/pages/ApplyFinish/index.js
> +        <ApplyFinishContentsLine>저희 멋쟁이사자처럼 명지대(자연) 11기를 위한</ApplyFinishContentsLine>
ApplyFinishContentsLine를 라인별로 나누지 마시고, 하나의 태그 안에서 문장을 작성하되 줄바꿈은 <br/>태그를 사용하면 구현이 더 깔끔하게 될 것 같아요!
글자 정렬은 text-align으로 하구요
충분히 없앨 수 있는 컴포넌트의 반복입니다 :(

2023-02-05 13:57 UTC, Bhanjo approved these changes
고생하셨습니다!

2023-02-05 18:23 UTC, harksu approved these changes
고생하셨습니다 👍

2023-02-09 07:11 UTC, merged