지원 메인페이지 모바일 버전 클릭 이벤트
mju-likelion/x-rated pull request #26
Opened 2023-02-07 15:01 UTC by yhyem

2023-02-08 13:27 UTC, Bhanjo commented on src/pages/ApplyMain/PartInfoMobile.js
> +  };
이건 최적화에 관련된 이야기지만..
`setIsClick(!isClick)`을 하게된다면 컴포넌트 내부의 정보인 `isClick`을 참조하게됩니다! 그러면 리렌더 발생시 onDisplay 함수를 재선언 하면서 성능이 떨어져요

성능 개선을 위해 `useCallback`을 사용할 수 있는데, 다음과 같이하면 onDisplay 함수는 최초 렌더링시 딱 한 번 선언되고 그 후로는 이미 선언된 함수를 재사용 가능하게됩니다!

```
const onDisplay = () => useCallback({
  setIsClick(prev => !prev); // 세터의 함수형 사용
}, [])
```

이렇게되면 컴포넌트 내부의 state에 depth가 의존되지 않으니 최초 한 번 선언 후 계속해서 재사용하므로 성능 관점에서 개선됩니다!

이제 여기서 좀 더 따져봐야하는건, 과연 이 페이지에서 useCallback 사용으로 성능 개선이 이루어졌나 보는거에요
useCallback, useMemo를 남용하는 것은 오히려 성능이 떨어지는 경우가 있기 때문이에요

한번 시간난다면 이 둘을 적용해서 렌더링 시간을 비교해보는 것도 리액트 배우는데 진짜 도움 될거에요

2023-02-08 13:27 UTC, Bhanjo commented on src/pages/ApplyMain/PartInfoMobile.js
> +      )}
`isClick`이라는 state에 의해 분기되는 부분이 두 개나 발생하고 있어요
아예 `isClick`이 true일 때 컴포넌트, false일 때 컴포넌트를 나누고 렌더링 하는것이 유지보수 관점에서 좋아보입니다!

2023-02-08 14:58 UTC, yhyem commented on src/pages/ApplyMain/PartInfoMobile.js
> +  };
아! 기능 구현 전에 usestate랑 클릭이벤트로만 구현해둔거 였는데 너무 좋은 정보네요!!
최적화 관련해선 아무래도 관련 지식이 제가 떨어지다 보니깐.. 좋은 정보 감사합니다 **갓한조**

2023-02-09 13:02 UTC, yhyem commented on src/pages/ApplyMain/PartInfoMobile.js
> +      )}
아!!! 알겠습니다 수정할게요 👍

2023-02-10 17:04 UTC, ndaemy requested changes

2023-02-10 17:04 UTC, ndaemy commented on src/pages/ApplyMain/PartData.js
>  };
이거.. 이러면 안될 것 같은데요
만약 index 가 정말 필요하다면 배열로 만드는게 맞을 것 같고, 
그게 아니라면 key 를 가지고 객체를 특정하는게 나을 것 같아요

2023-02-10 17:04 UTC, ndaemy commented on src/pages/ApplyMain/PartInfo.js
> +  font-family: 'Montserrat', sans-serif;
요기는 globalStyle 로 적용이 안되서 따로 폰트를 적용한건가요?

2023-02-10 17:04 UTC, ndaemy commented on src/pages/ApplyMain/index.js
> +  const [isClick, setIsClick] = useState([false, false, false]);
1. click은 동사니까 만약 is 가 붙는다면 isClicked 가 맞는 표현일 것 같아요.
2. isClicked 라고 하면 타입이 boolean 이여야 할 것 같아서, 타입이 boolean[] 이라면 네이밍을 조금 바꿔보면 좋을 것 같습니다 🤔

2023-02-10 17:05 UTC, yhyem commented on src/pages/ApplyMain/PartInfo.js
> +  font-family: 'Montserrat', sans-serif;
이게 지금 한글 영어 폰트가 섞여버려서 (영어인데도 한글폰트를 사용해야하는 경우가 존재합니다!)
그래서 가장 리소스가 적은 방식이 영어폰트 사용 부분이 적어서 영어폰트 사용하는 곳 (헤더/푸터/메인) 에서만 영어폰트 불러오고 나머지는 한글폰트 우선적용으로 논의된 상태입니당

2023-02-10 17:08 UTC, yhyem commented on src/pages/ApplyMain/PartData.js
>  };
key........가 있었네요 제가 바로 수정하겠습니다 😭

2023-02-10 17:38 UTC, yhyem commented on src/pages/ApplyMain/PartInfo.js
> +  font-family: 'Montserrat', sans-serif;
문제 해결 프로세스도 이슈탭에 따로 작성해 뒀습니다! 여기 혹시 참고용 으로 두고갈게요.. https://github.com/mju-likelion/x-rated/issues/32

2023-02-10 17:41 UTC, Bhanjo approved these changes

2023-02-10 17:41 UTC, Bhanjo commented on src/pages/ApplyMain/MobileClick.js
> +import React from 'react';
이건 선택이지만 React import는 없어도 됩니다!

2023-02-10 18:13 UTC, ndaemy requested changes

2023-02-10 18:13 UTC, ndaemy commented on src/pages/ApplyMain/index.js
> +  const [clikedArray, setClickedArray] = useState([false, false, false]);
여기 오타있어요..!
```suggestion
  const [clickedArray, setClickedArray] = useState([false, false, false]);
```

요거 `Commit suggestion` 버튼 클릭하시면 바로 수정 가능합니다!

2023-02-10 18:13 UTC, ndaemy commented on src/pages/ApplyMain/index.js
> +      return <PartInfoMobile partInfo={apply} key={index} handleClick={handleClick} isSelected={clikedArray[index]} />;
여기도 같이 수정되어야겠군요
```suggestion
      return <PartInfoMobile partInfo={apply} key={index} handleClick={handleClick} isSelected={clickedArray[index]} />;
```

2023-02-10 18:13 UTC, ndaemy commented on src/pages/ApplyMain/index.js
> +  const handleClick = idx => {
요건 Request changes 정도는 아닌데, 그냥 지나가는 의견입니당
저는 최근에는 index 혹은 i 라는 변수명만 많이 봤던 것 같아요! 뭔가 요즘은 idx 는 잘 안보이는 너낌입니다

2023-02-10 18:13 UTC, ndaemy commented on src/pages/ApplyMain/index.js
> +    let newArr = clikedArray;
이러면 shallow copy 가 되어버려서 clickedArray 도 수정되어 버립니다.
그런데 React state 는 그 특성상 수정되면 안되잖아요? 따라서 아래처럼 바뀌면 됩니다

```suggestion
    let newArr = [...clickedArray];
```

2023-02-10 18:13 UTC, ndaemy commented on src/pages/ApplyMain/index.js
> +    if (newArr[idx] == true) {
`==` 쓰시면 안됩니다 :bbadda:

```suggestion
    if (newArr[idx] === true) {
```

2023-02-10 18:13 UTC, ndaemy commented on src/pages/ApplyMain/index.js
>    const [innerWidth, setInnerWidth] = useState(window.innerWidth);
이거 도저히.. CSS로는 처리가 안되는거죠..? 😭

2023-02-10 18:14 UTC, yhyem commented on src/pages/ApplyMain/index.js
> +    if (newArr[idx] == true) {
죄..죄송하비다

2023-02-10 18:15 UTC, yhyem commented on src/pages/ApplyMain/index.js
> +  const [clikedArray, setClickedArray] = useState([false, false, false]);
세상이.. 좋아졌군요..

2023-02-10 18:33 UTC, yhyem commented on src/pages/ApplyMain/index.js
>    const [innerWidth, setInnerWidth] = useState(window.innerWidth);
제가 물론 부족한거 일순 있지만,, 화면에 따라 변경 내용이 많다보니까 아무래도 CSS로 처리하기엔 ,, 조금 어려운거 같아요

2023-02-10 18:44 UTC, ndaemy approved these changes
반드시 수정해야 할 것들은 아니라서 Approve 합니다! 혹시 수정할거라면 수정하시고 알아서 머지하시면 될듯!

2023-02-10 18:44 UTC, ndaemy commented on src/pages/ApplyMain/MobileNoClick.js
> +        <PartImage part={partInfo.value} width={'155.65px'} height={'117.13px'} />
어이쿠.. 이거 지금 봤는데
1. 소수점 px 가 디자인 의도가 맞나요? 아니라면 수정해야 할 것이고
2. 맞다면 소수점 px는 디자이너님께 의도가 맞는지 여쭈어보시길..

2023-02-10 18:44 UTC, ndaemy commented on src/pages/ApplyMain/index.js
>    const [innerWidth, setInnerWidth] = useState(window.innerWidth);
이번엔 이렇게 머지하시고 나중에 리팩토링 가능하면 해보시죠!

2023-02-10 18:44 UTC, ndaemy commented on src/pages/ApplyMain/index.js
> +    if (newArr[index] === true) {
이제 다시 보니 여기는 줄여서 쓸 수 있을 것 같아요
```suggestion
    if (newArr[index]) {
```

2023-02-10 18:47 UTC, yhyem commented on src/pages/ApplyMain/index.js
> +    if (newArr[index] === true) {
저는 왜 이런 쉥각을 못할ㄲㅏ요????

2023-02-10 18:49 UTC, yhyem commented on src/pages/ApplyMain/MobileNoClick.js
> +        <PartImage part={partInfo.value} width={'155.65px'} height={'117.13px'} />
있죠... 분명이 소수점이었는데요...... 지금보니 소수점이 아니에요 이건 분명 세상이 저에게 거짓말을 하고있어요

2023-02-10 19:01 UTC, merged