feat: apply main page 구현
mju-likelion/x-rated pull request #3
Opened 2023-01-24 15:45 UTC by yhyem

2023-01-24 16:34 UTC, harksu requested changes
참고 한번 해주시면 좋을 것 같습니다👍

2023-01-24 16:34 UTC, harksu commented on src/pages/ApplyMain/ApplyMainTop.js
> +import { Theme } from '../../styles/Theme';
프로바이더에서 하위 컴포넌트에 이미 제공을 해주기때문에 해당 import문은 사용하지 않아도 된다고 배웠습니다! @ndaemy  맞죠?

2023-01-24 16:34 UTC, harksu commented on src/pages/ApplyMain/ApplyMainTop.js
> +  color: ${Theme.Colors.BLUE1};
그래서 해당 코드는 위에서 언급했던 프로바이더에서 props로 전달받아서 사용할 수 있습니다 :) 
웹파트끼리 코드 스타일을 구조분해할당으로 나눠서 코드를 작성하면 더 통일성 있을 것 같아요!

2023-01-24 16:34 UTC, harksu commented on src/pages/ApplyMain/ApplyMainTop.js
> +        <div style={{ display: 'flex' }}>
해당 인라인 스타일이 적용되는 div태그가 반복되는데 TitleBox와 같은 네이밍을 가진 스타일컴포넌트로 명시하는건 어떨까요?

2023-01-24 16:34 UTC, harksu commented on src/pages/ApplyMain/PartInfo.js
> +const PartInformation = props => {
const PartInformation ={partImg,partTitle} => { ....}과 같은 구조 분해할당도 가능할 것 같은데, 혹시 해석의 편의성을 위해서 의도적으로 작성하신걸까요?

2023-01-24 16:34 UTC, harksu commented on src/pages/ApplyMain/index.js
> +            partImg={apply.image}
apply에 관련된 property들도 고의적으로 구조분해할당 안하신걸까요~?

2023-01-24 18:31 UTC, ndaemy commented on src/pages/ApplyMain/ApplyMainTop.js
> +import { Theme } from '../../styles/Theme';
예압 맞습니당
[ThemeProvider](https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/models/ThemeProvider.tsx#L72-L84) 는 내부적으로 `useContext`를 사용하기 때문에 전역상태처럼 사용할 수 있어요.

2023-01-24 18:37 UTC, ndaemy commented
혹시 이거 WIP인걸까요? 코드리뷰를 해도 되는건가 해서 여쭤봅니다!

2023-01-25 00:52 UTC, yhyem commented on src/pages/ApplyMain/ApplyMainTop.js
> +import { Theme } from '../../styles/Theme';
감사합니다.......... 수정할게요!!!

2023-01-25 00:53 UTC, yhyem commented on src/pages/ApplyMain/ApplyMainTop.js
> +        <div style={{ display: 'flex' }}>
굿.. 아이디어.....

2023-01-25 00:55 UTC, yhyem commented on src/pages/ApplyMain/index.js
> +            partImg={apply.image}
고의적인건 아니었고.. 수정하는게 더 좋을거 같네요 😂

2023-01-25 00:56 UTC, yhyem commented
> 혹시 이거 WIP인걸까요? 코드리뷰를 해도 되는건가 해서 여쭤봅니다!

WIP 이긴 한데 언제든 코드 리뷰는 해주셔도 좋아요!!

2023-01-25 10:08 UTC, ndaemy requested changes

2023-01-25 10:08 UTC, ndaemy commented on src/pages/ApplyMain/PartInfo.js
> +    <PartInformationDiv style={partInfo.value === 'SERVER' ? { margin: '30px' } : {}}>
styled component 네이밍 할 때 해당 태그 자체를 이름에 넣는 경우는 별로 없습니다. Div 를 쓰고 싶다면 Block 이나 Wrapper 를 suffix 로 붙이는게 더 흔한 컨벤션이에요

2023-01-25 10:08 UTC, ndaemy commented on src/pages/ApplyMain/index.js
> +      <ProgressButton style={{ margin: '100px auto 0', color: 'white', fontWeight: '700' }}>지원하기</ProgressButton>
styled component 를 쓰기로 했으면 인라인 스타일링은 지양합시다!

2023-01-25 15:15 UTC, Bhanjo commented on src/pages/ApplyMain/ApplyMainTop.js
> +      <div style={{ display: 'block' }}>
inline style은 지양해주세요!

2023-01-25 15:15 UTC, Bhanjo commented on src/pages/ApplyMain/ApplyMainTop.js
> +  color: ${props => props.theme.Colors.BLUE1};
[여기](https://github.com/mju-likelion/x-rated/pull/2/files/26d031fe7c03cdad30618617f691572f2070ec1b)를 보면 theme 사용 시 비구조화 할당으로 통일하기로 되어있는데 참고해서 변경해주세요!

다른 부분들도 적용 부탁합니다~

2023-01-25 15:15 UTC, Bhanjo commented on src/pages/ApplyMain/PartData.js
> +];
`PartDate.js` 파일은 단순히 목업 데이터를 위한 파일인가요? 아니면 이 파일에서 데이터 패치가 이루어지나요?

데이터 패치 동작 예정이라면 비동기 처리를 미리 해놓는 것을 추천합니다!

2023-01-25 15:15 UTC, Bhanjo commented on src/pages/ApplyMain/PartData.js
> +import Design from '../../assets/images/icon_design.svg';
svg를 어떻게 쓸 예정인가요? 이미지 태그로 쓸 예정인가요? 아니면 svg 컴포넌트 처럼 쓸건가요?

svg의 특징을 살리려면 컴포넌트처럼 쓰는 것을 권장합니다!

2023-01-25 15:15 UTC, Bhanjo commented on src/pages/ApplyMain/PartInfo.js
> +export default PartInformation;
리액트 컴포넌트의 default export는 가장 아래에 있는 것이 일반적인 것으로 알고있는데 맞나요?? @유예빈

맞다면 export를 가장 아래로 내려주세요!

2023-01-26 00:31 UTC, yhyem commented on src/pages/ApplyMain/PartData.js
> +];
패치는 안이루어집니다!

2023-01-26 00:32 UTC, yhyem commented on src/pages/ApplyMain/index.js
> +      <ProgressButton style={{ margin: '100px auto 0', color: 'white', fontWeight: '700' }}>지원하기</ProgressButton>
저친구는 공통 컴포넌트를 활용한건데 이러한 경우에도 인라인 스타일링이 아니라 다른 방식으로 해야하나요??

2023-01-26 12:54 UTC, harksu reviewed
👍

2023-01-26 12:54 UTC, harksu commented on src/pages/ApplyMain/PartInfo.js
>    background-color: ${props => props.theme.Colors.GRAY1};
구조 분해 할당 +1 👍

2023-01-26 12:54 UTC, harksu commented on src/pages/ApplyMain/index.js
>        <ProgressButton style={{ margin: '100px auto 0', color: 'white', fontWeight: '700' }}>지원하기</ProgressButton>
해당 스타일 코드는 스타일 컴포넌트로 상속받는 형식이 더 가독성이 좋을 것 같습니다 :)

2023-01-26 13:14 UTC, yhyem commented on src/pages/ApplyMain/index.js
>        <ProgressButton style={{ margin: '100px auto 0', color: 'white', fontWeight: '700' }}>지원하기</ProgressButton>
엇 가장 최근 커밋 기록에 수정 해두었씁니다

2023-01-26 13:14 UTC, yhyem commented on src/pages/ApplyMain/PartInfo.js
>    background-color: ${props => props.theme.Colors.GRAY1};
수정해두었습니다!

2023-01-26 13:34 UTC, ndaemy commented on src/pages/ApplyMain/PartInfo.js
> +export default PartInformation;
그건 정하기 나름일 것 같아요! 해당 컴퍼넌트 선언 직후 export default 할지, 아니면 파일 맨 밑에서 할지는 정하기 나름인데, 대신 다른 개발자분들이랑은 통일성 있게 맞추시죠!

2023-01-26 16:56 UTC, ndaemy commented
PR 이름 바꿔주세요~

2023-01-27 06:25 UTC, harksu commented on src/pages/ApplyMain/PartInfo.js
> +export default PartInformation;
저는 개인적으로 스니펫 형식 따라가는 파라서, 컴퍼넌트 선언 직후가 좋은 것 같숩니다

2023-01-27 10:06 UTC, Bhanjo approved these changes
추후 공통 버튼 풀리퀘 닫히면 `ProgressButton`을 `Button` 공통 컴포넌트로 바꿔주세요!

2023-01-27 16:12 UTC, ndaemy requested changes

2023-01-27 16:12 UTC, ndaemy commented on src/pages/ApplyMain/PartData.js
> +import { ReactComponent as Design } from '../../assets/images/icon_design.svg';
다른 분 PR 에도 코드리뷰 남겼었는데, svgr 을 사용하기로 고민해보는건 어떠신가요?

2023-01-27 16:12 UTC, ndaemy commented on src/pages/ApplyMain/PartInfo.js
> +        <img src={iconPlus} style={{ marginLeft: 'auto', marginRight: '24px' }} />
인라인 스타일링은 지양해주세요!

2023-01-27 16:12 UTC, ndaemy commented on src/pages/ApplyMain/index.js
> +      <ApplyMainTop></ApplyMainTop>
Empty component 는 self-closing 하도록 해주세요!

2023-01-27 16:12 UTC, ndaemy commented on src/pages/ApplyMain/PartData.js
> +export const PartData = [
React component 나 TypeScript type 이 아니라면 camelCase 나 UPPER_CASE를 사용해주세요!

2023-01-27 16:12 UTC, ndaemy commented on src/pages/ApplyMain/index.js
> +`;
요건 globalStyle 로 빼보는게 어떨까요? 프로젝트 내부의 모든 link 가 text-decoration: none; 하다면요!

2023-01-27 16:13 UTC, ndaemy commented
여기도 PR 이름은 좀 더 human-readable 하게 바꿔보는건 어떨까요?

2023-02-01 04:59 UTC, harksu requested changes
👍

2023-02-01 04:59 UTC, harksu commented on src/pages/ApplyMain/PartInfo.js
> +        <partInfo.image />
이게 태그로 들어가는게 맞나요 ..?

2023-02-01 04:59 UTC, harksu commented on src/pages/ApplyMain/PartInfo.js
> +  display: none;
display가 none이면 밑에 css 코드들 의미 없지 않나요..? none이면 공간도 차지 안하는걸로 알고 있는데

2023-02-01 04:59 UTC, harksu commented on src/pages/ApplyMain/index.js
> +  const [innerWidth, setInnerWidth] = useState(window.innerWidth);
👍

2023-02-01 04:59 UTC, harksu commented on src/pages/ApplyMain/index.js
> +          innerWidth > 1199 ? (
해당 로직에서 1199와 599와 같은, 디스플레이 크기를 나타내는 값들은 상수 처리를 하는것이 더 가독성이 좋아보입니다
1199라는 값이 어떤 값인지 저희가 디스플레이 크기를 외웠으니까 이해하는거지, 코드가 많아지고 복잡해지면 헷갈릴 것 같아요!

2023-02-01 04:59 UTC, harksu commented on src/pages/ApplyMain/index.js
> +          innerWidth > 1199 ? (
그리고 jsx 내부에서 조건문이 다소 길어서, 가독성이 좋지 않다는 생각이 듭니다 apply와 index를 받는 함수를 위에서 선언하고 이 함수를 호출로 변경하는 방식은 어떨까요?

2023-02-01 05:03 UTC, yhyem commented on src/pages/ApplyMain/PartInfo.js
> +  display: none;
엇 hover시 display:block으로 변경됩니다!

2023-02-01 06:21 UTC, harksu commented on src/pages/ApplyMain/PartInfo.js
> +  display: none;
제가 놓쳤군요 핳 ..

2023-02-01 14:21 UTC, yhyem commented on src/pages/ApplyMain/PartInfo.js
> +        <partInfo.image />
svg의 경우 PartData에 선언한 이름 (as ...)이 <...> 형태로 사용이 되는데 제 코드에선 해당 이름이 partInfo.image에 저장이 되어 있어서,, 이러한 방식을 사용했는데 혹시 다른 방식이 있을까요??

2023-02-01 14:24 UTC, harksu commented on src/pages/ApplyMain/PartInfo.js
> +        <partInfo.image />
이거는 몰라서 물어본거에요!!! 저는 svg 받아올 때 선언한 이름을 다른 컴포넌트로 감싸서 사용해서 잘 몰랐습니다 👍

2023-02-01 14:54 UTC, yhyem commented on src/pages/ApplyMain/index.js
> +`;
요고는 머지 이후에 한번 논의를 해보도록 하게씁니당

2023-02-01 14:55 UTC, harksu approved these changes
고생하셨습니다 👍

2023-02-01 14:58 UTC, harksu requested changes

2023-02-01 14:58 UTC, harksu commented on src/pages/ApplyMain/ApplyMainTop.js
> +  @media ${({ theme }) => theme.devices.MOBILE} {
이게 확장성을 대비해서 mobile을 선언해놓기는 했는데.. 350px 밑으로도 어느정도의 스타일링을 제공하기 위해서 해당 코드들은 미디어 쿼리 제외하시고 font-weight: 700과 같은 위치에(태블릿보다 작은 사이즈는 모두 모바일 반응형으로) 선언하시는게 더 좋을 것 같습니다.
제가 이부분을 놓쳤네요

2023-02-01 15:02 UTC, ndaemy requested changes

2023-02-01 15:02 UTC, ndaemy commented on src/pages/ApplyMain/ApplyMainTop.js
> +  }
기본값은 주시는게 나아요! 이럴 경우 350px 미만일 때는 `margin-bottom: 0;` 이렇게 적용되어버릴테니가 모바일을 체크 안해주시면 됩니다!

2023-02-01 15:02 UTC, ndaemy commented on src/pages/ApplyMain/PartData.js
> +];
이건 순서가 중요한 데이터가 아니라 각각의 뜻이 중요한 데이터니까 배열이 아니라 객체가 맞는 타입으로 보여요. 아래처럼 바꿔보면 어떨까요? (바꾸시면 관련 코드들도 조금 더 이뻐질 것 같습니다)

```suggestion
export const PART_DATA = {
  web: {
    image: Web,
    value: 'WEB',
    info: 'React를 활용하여 협업을 통해서 유지보수성 및 UI/UX를 고려한 실제 웹 서비스를 제공해요.',
    tool: '이것 저것',
  },
  server: {
    image: Server,
    value: 'SERVER',
    info: '실제 서비스에 사용되는 API 서버를 설계하고, NestJS를 통해 실제 작동하는 서버로 구현/배포해요.',
    tool: '이것 저것',
  },
  design: {
    image: Design,
    value: 'DESIGN',
    info: '나의 아이디어를 기획, 디자인하고 개발 파트와의 협업을 통해 실제 서비스로 만들어요.',
    tool: '이것 저것',
  },
};
```

2023-02-01 15:02 UTC, ndaemy commented on src/pages/ApplyMain/PartInfo.js
> +        <partInfo.image />
저는 개인적으로는 이런 식의 컴퍼넌트 사용은 추천하지 않습니다. 무슨 컴퍼넌트가 불리는지 명확히 보이지 않기 때문인데요, 위의 코드리뷰처럼 `PART_DATA`를 object 로 바꾸고 나서 아래처럼 바꿔보면 어떨까 싶어요 (물론 더 좋은 코드가 있을 수도 있구요!)

```jsx
// 선언
const PartImage = ({ part })) => {
  switch (part) {
    case 'web':
      return <WebImage />;
    case 'server':
      return <ServerImage />;
    case 'design':
      return <DesignImage />;
    default:
      return <></>;
};

// 사용
<>
  <PartImage part={part.value} />
</>
```

2023-02-01 15:02 UTC, ndaemy commented on src/pages/ApplyMain/index.js
> +  });
resize에 대해 eventListener 를 달아준건 좋은데, 리액트 useEffect 에서 달아줄 경우에는 이 컴퍼넌트가 언마운트 될 때 저 리스너도 떼어주셔야 합니다. 아래처럼 작성하면 됩니다. 나중에 useEffect cleanup function 에 대해 더 공부해보시면 좋을거에요!

```suggestion
  useEffect(() => {
    const resizeListener = () => {
      setInnerWidth(window.innerWidth);
    };
    window.addEventListener('resize', resizeListener);
    return () => {
      window. removeEventListener('resize', resizeListener);
    };
  });
```

2023-02-01 15:05 UTC, mywhzy reviewed
이 부분 피그마에는 명지대(자연)으로 되어있는데 캠퍼스명시 안 하기로 빠진걸까용?

2023-02-01 15:08 UTC, mywhzy reviewed
이 부분 피그마에는 명지대(자연)으로 되어있는데 캠퍼스명시 안 하기로 빠진걸까용?

2023-02-01 15:08 UTC, mywhzy commented on src/pages/ApplyMain/ApplyMainTop.js
> +        <LeftTitle>멋쟁이사자처럼 명지대</LeftTitle>
이 부분 피그마에는 명지대(자연)으로 되어있는데 캠퍼스명시 안 하기로 빠진걸까용? 여기 말하는 겁니다아..^__^

2023-02-01 15:08 UTC, yhyem commented on src/pages/ApplyMain/ApplyMainTop.js
> +        <LeftTitle>멋쟁이사자처럼 명지대</LeftTitle>
분명 없었는데... 언제 생겼죠....?? 감사합니다 전혀 몰랐어요

2023-02-01 15:10 UTC, harksu commented on src/pages/ApplyMain/index.js
> +  });
미친 코드리뷰 클라스 ..

2023-02-01 15:23 UTC, Bhanjo approved these changes
리뷰할 것들을 다른 분들이 다 하셔서... 다른 분들이 언급한 것들 업데이트 하면 merge 해도 될 것 같아요~ 고생하셨습니다 bb

2023-02-01 15:33 UTC, mywhzy approved these changes
우리 웹짱님 반응형 구현하느라 넘나리 고생 많으셨씁니다아 ❤❤

2023-02-01 17:02 UTC, harksu approved these changes
고생하셨습니다. 디자인 디테일은 추후에 디자이너님 컨펌받고 잡는걸로 👍

2023-02-01 17:26 UTC, ndaemy requested changes
전체적으로 피그마랑 css가 동일한지 점검이 필요해 보입니다..!

2023-02-01 17:26 UTC, ndaemy commented on src/pages/ApplyMain/ApplyMainTop.js
> +  margin-bottom: 25.5px;
CSS의 거의 대부분의 속성에는 소수점 쓰는 걸 추천하지 않습니다 왜냐하면 특정 브라우저들은 px 단위에 실수가 들어오는걸 처리를 못하기 때문입니다
혹시나 디자이너님이 이렇게 주셨다면 디자인 다시 해달라고 하셔야 합니다

2023-02-01 17:26 UTC, ndaemy commented on src/pages/ApplyMain/ApplyMainTop.js
> +  margin-bottom: 25.5px;
+ 현재 피그마는 30px 로 되어있네요!

2023-02-01 17:26 UTC, ndaemy commented on src/pages/ApplyMain/ApplyMainTop.js
> +const RightCont = styled.div`
RightCont 가 혹시 무슨 뜻이에요..?

2023-02-01 17:26 UTC, ndaemy commented on src/pages/ApplyMain/PartData.js
> +};
1. 리액트 컴퍼넌트의 파일명은 항상 해당 컴퍼넌트 자체인게 컨벤션입니다.
2. 해당 컴퍼넌트 안에서 사용되는 상수가 아닌 상수는 다른 파일 혹은 별도의 파일로 보내는 것이 일반적입니다.

2023-02-01 17:26 UTC, ndaemy commented on src/pages/ApplyMain/index.js
> +    margin-right: auto;
이럴 때는 위에처럼 줄여서 margin: ~~ 로 해보면 어떨까요?

2023-02-01 17:27 UTC, yhyem commented on src/pages/ApplyMain/ApplyMainTop.js
> +const RightCont = styled.div`
오른쪽.. 내용.. 대충 이런뜻..?

2023-02-01 17:40 UTC, ndaemy commented on src/pages/ApplyMain/ApplyMainTop.js
> +const RightCont = styled.div`
아싸리 RightContent 로 하시든.. 등으로 이름은 의미있게.. 누가 봐도 알아볼 수 있게.. 🙏

2023-02-01 17:42 UTC, yhyem commented on src/pages/ApplyMain/ApplyMainTop.js
> +const RightCont = styled.div`
알게씁니다 !!!

2023-02-01 17:54 UTC, ndaemy approved these changes
진짜 수고 많으셨습니다 🥳

2023-02-01 18:02 UTC, merged