메인 페이지 타이틀 컴포넌트 구현
mju-likelion/x-rated pull request #6
Opened 2023-01-26 16:42 UTC by harksu

메인 페이지에 들어가는 '지원서 작성하기' 공통 컴포넌트입니다

2023-01-26 16:42 UTC, harksu commented
반응형도 적용했습니당~

2023-01-26 16:49 UTC, ndaemy requested changes

2023-01-26 16:49 UTC, ndaemy commented on src/App.js
>  import GlobalStyle from './styles/GlobalStyle';
여기 import 문들 empty line 이랑 아닌거랑 구분이 뭐에요? 요거 eslint 에서 rule 로 강제해서 관리하시는게 좋을듯해요!

2023-01-26 16:49 UTC, ndaemy commented on src/App.js
> +        <PageMainTitle title="지원서 작성하기" />
요거는 Root 가 아니라 route 에 종속적인 component 여야 하는거 아닌가요?

2023-01-26 16:52 UTC, ndaemy commented on src/App.js
>  import GlobalStyle from './styles/GlobalStyle';
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md

2023-01-26 16:52 UTC, ndaemy commented on src/App.js
>  import GlobalStyle from './styles/GlobalStyle';
참고우

2023-01-26 16:52 UTC, ndaemy commented
PR 이름 바꿔주세요~

2023-01-26 16:54 UTC, harksu commented on src/App.js
>  import GlobalStyle from './styles/GlobalStyle';
이거 제가 안했지만 우선 알겠니다.. 👍

2023-01-26 16:54 UTC, harksu commented on src/App.js
> +        <PageMainTitle title="지원서 작성하기" />
넵 해결했습니다 👍

2023-01-27 10:08 UTC, Bhanjo approved these changes

2023-01-27 10:08 UTC, Bhanjo commented on src/components/PageMainTitle.js
> +  font-weight: 700px;
폰트 굵기를 `700`으로 안하고 `700px`로 해도 적용 되나요..? 제가 몰라서ㄷㄷ

2023-01-27 16:15 UTC, ndaemy requested changes

2023-01-27 16:15 UTC, ndaemy commented on src/components/PageMainTitle.js
> +  font-weight: 700px;
어휴 안되죠 무슨 소리

2023-01-27 16:15 UTC, ndaemy commented on src/components/PageMainTitle.js
> +  @media (max-width: 1199px) {
차라리 깔끔하게 `@media (min-width: 1200px) { ... }` 이런 식으로 해볼 순 없을까요?

2023-01-27 16:53 UTC, harksu commented on src/components/PageMainTitle.js
> +  font-weight: 700px;
죄송합니다 휴먼에러에요..^^

2023-01-27 16:53 UTC, harksu commented on src/components/PageMainTitle.js
> +  @media (max-width: 1199px) {
넵.. :(

2023-01-27 17:09 UTC, harksu commented on src/components/PageMainTitle.js
> +  @media (max-width: 1199px) {
해당 코드 작성할 때, 큰 device view부터 고려해서 코드 라인수를 줄인건데, min-width로 하면 코드 라인수가 길어져서 1199px같이 깔끔하지 않은 수는 차라리 theme로 빼서 props로 받는 방식은 어떨까요?

2023-01-27 18:06 UTC, harksu commented on src/App.js
>  import GlobalStyle from './styles/GlobalStyle';
#9  참조 부탁드려요!

2023-01-27 20:20 UTC, ndaemy commented on src/styles/Theme.js
> +    PHONE: `(max-width: 599px) `,
아.. 99 단위 진짜 보기 싫은데.. 이거밖에 답이 없는거죠..? ㅋㅋㅋㅋ

2023-01-28 08:56 UTC, ChoiWonYu approved these changes
고생하셨습니다!

2023-01-28 08:56 UTC, ChoiWonYu commented on src/components/PageMainTitle.js
> +  color: ${({ theme }) => theme.Colors.WTHIE};
White 오타났네영 심신미약 인정합니다
이것만 고치면 될 거 같아요!

2023-01-28 14:03 UTC, harksu commented on src/styles/Theme.js
> +    PHONE: `(max-width: 599px) `,
지금 수정하고있습니다 ^^

2023-01-28 14:03 UTC, harksu commented on src/components/PageMainTitle.js
> +  color: ${({ theme }) => theme.Colors.WTHIE};
핳... 👍

2023-01-28 15:36 UTC, ndaemy requested changes
죄송 ^^

2023-01-28 15:36 UTC, ndaemy commented on src/components/PageMainTitle.js
> +  }
다른 PR에서인가.. 그 theme 밑에 대문자로 시작하는거로 Request Changes 걸어놓은 적이 있는데, 
상수에 관련된 녀석이라면 camelCase 혹은 UPPER_CASE 를 써주세요
`Colors`하고 `Devices` 이야기하는 겁니당

2023-01-28 15:36 UTC, ndaemy commented on src/styles/Theme.js
> +  Devices: {
👍

2023-01-28 15:38 UTC, harksu commented on src/components/PageMainTitle.js
> +  }
아 제가 그 부분을 놓쳤나보네요! 제쪽에서 한번에 수정하겠습니다

2023-01-28 15:53 UTC, ndaemy approved these changes
고생하셨습니다

2023-01-28 15:55 UTC, merged