Footer 컴포넌트 적용
mju-likelion/x-rated pull request #8
Opened 2023-01-26 17:44 UTC by mywhzy

아직 반응형 적용 x PC 1920px기준으로만 작업했습니다아..

2023-01-27 10:15 UTC, Bhanjo reviewed
헤더와 마찬가지로 푸터 또한 컴포넌트 함수를 위로, 스타일 함수를 아래로 내려주세요! 다른 분들이 작성하신 방식 참고하면 됩니다!

2023-01-27 16:17 UTC, ndaemy commented on src/components/Footer.js
> +        <MailDefaultIcon />
요거 `Default` 가 infix 로 붙는 이유가 있나요?

2023-01-27 16:42 UTC, mywhzy commented on src/components/Footer.js
> +        <MailDefaultIcon />
> 요거 `Default` 가 infix 로 붙는 이유가 있나요?

이게 초반에 svg이미지가 default/hover시 두 종류로 나눠져있어서 미리 네이밍을 저렇게 했던건데! 아직 커밋 찍진 않았지만 일단 default svg에서 hover시 fill 색상을 바꿀 예정이라 그냥 ~Icon으로 바꿔도 될 거 같습니당!! 수정하겠습니당

2023-01-28 16:34 UTC, mywhzy commented
변경사항 -
1. svg icon 파일이 일반/hover시로 나뉘어있었는데 기본 svg파일에 hover 시 인라인 스타일로 색상 변경되게 수정
2. icon 클릭 시 link 이동 및 이메일 복사 기능 추가

2023-01-28 16:45 UTC, ndaemy requested changes

2023-01-28 16:45 UTC, ndaemy commented on src/components/Footer.js
> +import { ReactComponent as MailIcon } from '../assets/images/icon_mail_default.svg';
333
svgr 적용해보시는거 어떨까요

2023-01-28 16:45 UTC, ndaemy commented on src/components/Footer.js
> +        <MediIcon onClick={() => handleClick(3)} />
위의 suggestion 을 merge 하신다면 여기도 조금 더 의미있게 갈 것 같아요
`handleClick('instagram');` 처럼요

2023-01-28 16:45 UTC, ndaemy commented on src/components/Footer.js
> +        <MailIcon onClick={handleCopyEmail} />
이메일을 눌렀을 때 복사하는게 더 자연스러운 경험일까요 아니면 메일 보내기가 되는게 더 자연스러운 경험일까요?
만약 후자라면 `<a link="mailto:mju@likelion.org><MailIcon /><a>` 이런 식으로 처리가 가능할 것 같아요

2023-01-28 16:45 UTC, ndaemy commented on src/components/Footer.js
> +    navigator.clipboard.readText(mjuEmail) ? alert('이메일이 복사되었습니다.') : alert('이메일 복사 오류입니다.');
alert는 사용을 지양합니다. 필요하다면 커스텀 모달 등으로 빼주세요.

2023-01-28 16:45 UTC, ndaemy commented on src/components/Footer.js
> +  color: ${({ theme }) => theme.Colors.GRAY2};
지금 develop을 merge 하시면 여기 코드를 바꿔야 정상 작동 할듯 싶습니다! 추후 conflict 을 방지하기 위해서 지금 처리해두시는게 좋을 것 같아요

2023-01-30 15:09 UTC, mywhzy commented on src/components/Footer.js
> +  color: ${({ theme }) => theme.Colors.GRAY2};
브랜치 머지+수정 :wanwan: 입니당

2023-01-30 15:10 UTC, mywhzy commented on src/components/Footer.js
> +    navigator.clipboard.readText(mjuEmail) ? alert('이메일이 복사되었습니다.') : alert('이메일 복사 오류입니다.');
일단 토스트메시지 구현 전까지 미완성 기능으로 분리하고 alert는 지워두겠습니다!

2023-01-30 15:11 UTC, mywhzy commented on src/components/Footer.js
> +        <MediIcon onClick={() => handleClick(3)} />
더 직관적이고 좋아졌네요오!! 피드백 감사합니다 얘두 반영 :wanwan:

2023-02-01 14:51 UTC, harksu approved these changes
고생하셨습니다 :)

2023-02-01 15:34 UTC, Bhanjo approved these changes
고생하셨습니다~

2023-02-01 15:34 UTC, Bhanjo commented on src/components/Footer.js
> +  };
이런 고오급 로직 누구한테 전수받은거에요?

2023-02-01 15:34 UTC, Bhanjo commented on src/components/Footer.js
> +  };
비동기 catch로 예외케이스 대응 잘했고, 체크 로직으로 복사 검증까지 잘 헀네요 bbb

2023-02-01 15:40 UTC, mywhzy commented on src/components/Footer.js
> +  };
[https://88240.tistory.com/528](url)
공익을 위해 공유합니다 헤헤

2023-02-01 18:26 UTC, ndaemy requested changes

2023-02-01 18:26 UTC, ndaemy commented on src/components/Footer.js
> +  const mjuEmail = 'mju@likelion.org';
1. urlList 를 socialLinks 로 이름을 바꾸고
2. mjuEmail을 socialLinks의 필드로 넣어보면 어떨까요?

둘 다 소셜 관련 데이터니까 하나의 객체로 묶는게 더 이쁠 것 같아서요!

2023-02-01 18:26 UTC, ndaemy commented on src/components/Footer.js
> +  };
이게 고급 로직인 건 맞는데, UX 적인 관점에서 하나만 피드백할게요
보통 외부 사이트로 가는건 새로운 탭에서 열기 때문에 `<a href="~" target="_blank" rel="noopener noreferrer" />` 로 하는게 일반적입니다
위의 링크처럼 onClick 이면 잘 작동하지 않는 환경들이 있기도 하구요

2023-02-01 18:26 UTC, ndaemy commented on src/components/Footer.js
> +  };
이거 인앱 웹뷰면 권한 문제로 안 될 수도 있다고 알고 있어서, 카톡 등으로 열어서 테스트 꼭 해봐야 할 것 같아요

2023-02-01 18:26 UTC, ndaemy commented on src/components/Footer.js
> +  font-family: 'Montserrat';
요거 global 스타일로 빼고 한글일땐 Spoqa Han Sans 로, 영어일 땐 Montserrat 로 나오게 해주세요
font-family는 어지간하면 글로벌로 관리하는게 추후 유지보수에 용이합니다!

2023-02-01 18:26 UTC, ndaemy commented on src/styles/GlobalStyle.js
> +        font-family: 'Spoqa Han Sans Neo', 'Spoqa Han Sans JP', 'Montserrat', sans-serif;
이거 위에도 코드리뷰 달았는데, 이렇게 쓰면 영어도 Spoqa Han Sans Neo 가 먼저 적용됩니다
unicode-range 같은거 찾아보시면 방법 나올듯해요!

2023-02-03 00:03 UTC, Bhanjo approved these changes
고생하셨습니다~

2023-02-03 00:03 UTC, Bhanjo commented on src/components/Footer/SocialLinks.js
> +export const SOCIALLINKS = {
상수가 두 단어 이상일 경우 BIG_SNAKE_CASE로 해주세요~

2023-02-03 05:00 UTC, mywhzy commented on src/components/Footer/SocialLinks.js
> +export const SOCIALLINKS = {
앗 반영했습니당 감사합니다!

2023-02-03 06:52 UTC, merged